default_config:
automation: !include automation.yaml
frontend: !include configs/frontend.yaml
history: !include configs/logbook_history.yaml
recorder: !include configs/recorder.yaml
input_boolean: !include inputs/boolean.yaml
logbook: !include configs/logbook_history.yaml
script: !include_dir_merge_named scripts/
weather: !include configs/weather.yaml
map:
mobile_app:
sun:
system_health:
#updater:
discovery:
ios:

http:
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key

lovelace:
  mode: yaml

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  time_zone: !secret time_zone
  elevation: !secret elevation
  unit_system: metric
  external_url: !secret url
  auth_providers:
    - type: homeassistant

mqtt: !include_dir_merge_list mqtt/
group: !include configs/groups.yaml
camera: !include devices/cameras.yaml
sensor: !include_dir_merge_list sensors/
utility_meter: !include utility_meters/smart_plugs_energy.yaml
alexa: !include cloud_configs/alexa.yaml