- platform: darksky
  api_key: !secret darksky_api
  latitude: !secret latitude
  longitude: !secret longitude
  language: 'pt'
  units: ca 
  forecast:
    - 0
  monitored_conditions: 
    - sunrise_time
    - sunset_time
    - temperature
    - wind_speed
    - cloud_cover
    - humidity
    - pressure
    - visibility
    - hourly_summary
    - daily_summary
    - uv_index
    - nearest_storm_distance
