- platform: qbittorrent
  name: qBittorrent
  url: !secret qBittorrent_url
  username: !secret qBittorrent_user
  password: !secret qBittorrent_password

- platform: radarr
  api_key: !secret radarr_api_key
  host: !secret docker_machine
  port: !secret radarr_port 
  monitored_conditions: 
     - upcoming
     - diskspace
     - status
     - movies
  days: 7
  unit: TB 

- platform: radarr_upcoming_media
  api_key: !secret radarr_api_key
  host: !secret docker_machine
  port: !secret radarr_port 
  days: 120
  theaters: false
  max: 10

- platform: sonarr_upcoming_media
  api_key: !secret sonarr_api_key
  host: !secret docker_machine
  port: !secret sonarr_port
  days: 7
  max: 10

- platform: tautulli
  api_key: !secret tautulli_api_key
  host: !secret url
  port: !secret tautulli_port  
  ssl: True