db_url: !secret db_url

db_max_retries: 10 

db_retry_wait: 3

db_integrity_check: true

auto_purge: false

purge_keep_days: 365

commit_interval: 0

exclude: !include logs_exclude.yaml

include: !include logs_include.yaml